### ISSUE TITLE
Split repo

### ISSUE THREAD

**Issue by ilblackdragon** [near/rainbow-bridge-cli#280]
Starting the discussion about splitting the repo into it's own organization and multiple repos:
 - repo with Solidity contracts
 - repo with Rust libraries / contracts
 - repo with rainbow.js library
 - repo with rainbow CLI
 - repo with ERC-20 locker Sol + Rust
 - Additional example can be: ETH locker and later we can do NFT, etc.

Reasoning:
 - Solidity contracts need to be in separate repo to make sure other repos can depend on it (e.g. similar to OpenZeppelin contracts - https://github.com/OpenZeppelin/openzeppelin-contracts)
 - Rust doesn't really need to be, but it's cleaner if it?
 - rainbow javascript library is needed in multiple other places
 - CLI would be nice to use without needing to even close the code

Con:
 - Breaks the "monorepo" and leads to version linking / etc.

Additionally, CLI should be working with our existing `near` tooling more as well.

**Comment by nearmax** [comment]
Copying @ilblackdragon 's comment from the issue here:

> Name for CLI: rainbow or rainbowup?
> See #280
> Relayers should run independently and regular developers should not worry about it.
> E.g. regular developer flow
> 3.0 clone the locker contracts repo
> 3.1 (optionally) customize locker/minter contracts
> 3.2 rainbow build // builds current contracts in the repo: sol & rs
> 3.3 rainbow deploy '{"erc20": , "mintable-": , ...other params}'
> And then users can use the library can initiate transfers.

**Comment by ailisp** [comment]
I think this makes sense, both repo like current or separate repo works to me. Actually it's already a mixed of them (we have a submodule), we can move more repos as submodules

> Solidity contracts need to be in separate repo to make sure other repos can depend on it (e.g. similar to OpenZeppelin contracts - https://github.com/OpenZeppelin/openzeppelin-contracts)
> Rust doesn't really need to be, but it's cleaner if it?
> rainbow javascript library is needed in multiple other places
> CLI would be nice to use without needing to even close the code

Make sense

> Breaks the "monorepo" and leads to version linking / etc.

It's kind of pain as of now, I suggest we do separating after fixing all audit issues, by that time many parts have almost frozen and this is easier to handle

**Comment by nearmax** [comment]
For the context, we did split the code into multiple sub-components in this repository in the past and it made development and usage of the bridge very difficult, because we have lots of very complex interactions and code re-usage between multiple components, and until we arrive into a very clean and stable stage of the bridge it would hurt us more if start splitting it. For example, the following components share a lot of code:
* Client/prover contracts setup and initializations;
* Relays and watchdogs;
* Transfers;
E.g. we are going to add a feature where transfers should be able to relay a missing header, or transfers can verify Ed25519 signatures and automatically challenge, if needed; Contract initialization code uses the same contract wrapping code as the code that interacts with these contracts.

Also, I suggest RainbowCLI and RainbowLib to do standard transfers, like ERC20, because that's what most of the people are going to be expecting to do out of the box. It would be problematic if people would need to install a separate CLI tool just for ERC20 transfers.

Here is I how propose we split this repo after we are done with audit findings and Phase 1.5 push:
* rainbow-lib. Includes: rainbow-lib (contains the core code that someone can reuse for low-level work with the bridge, can do basic transfers and contract calls, contains relays and watchdog code, can initialize contracts), rainbow-cli (just a thin wrapper on rainbow-lib), rainbow-test-fixtures (spins up nearup and Ganache for testing);
* rainbow-eth. Solidity client/prover contracts and core use cases contracts, like ERC20, which should also serve as examples for people extending the bridge;
* rainbow-rs: Rust client/prover contracts and core use case contracts.

Btw, if we want people to be able to depend on the Solidity contracts, they need to be in npm as a separate package similarly to https://www.npmjs.com/package/@openzeppelin/contracts .

---

Addressing @ilblackdragon 's comments:

> CLI would be nice to use without needing to even close the code

Not sure I understand what it means.

> Solidity contracts need to be in separate repo to make sure other repos can depend on it (e.g. similar to OpenZeppelin contracts - https://github.com/OpenZeppelin/openzeppelin-contracts)

AFAIU, the typical way to depend on a Solidity contract is to publish it to npm and depend on the npm package: https://www.npmjs.com/package/@openzeppelin/contracts

> Relayers should run independently and regular developers should not worry about it.

The JS code used by the relays have a lot of intersection with other code. In the past we tried separating it and it made development really difficult.

> Relayers should run independently and regular developers should not worry about it. E.g. regular developer flow

I think this will be the development workflow:
1. Clone contracts repo;
2. Customize contracts;
3. Start local NEAR and ETH blockchains, initialize contracts, start relays;
4. Build the modified contracts and deploy them;
5. Use library to do transfers with local code.

Step 3 implies that developers would need to touch every component of the bridge, by installing them from npm or cloning repos.

**Comment by nearmax** [comment]
CC @chadoh

**Comment by nearmax** [comment]
@ailisp This seems to be done. Should we close it?

**Comment by ailisp** [comment]
@nearmax Yes,closing now
